### ISSUE TITLE
EVGA Precision X1 version 1.3.7.0 available

### ISSUE THREAD

**Issue by koitsu** [javydekoning/chocolatey-fanatec-packages#15]
Since October 2022: https://www.evga.com/EVGA/GeneralDownloading.aspx?file=EVGA_Precision_X1_1.3.7.0.zip

**Comment by javydekoning** [comment]
Yes, this repo already has it: 

https://github.com/javydekoning/chocolatey-fanatec-packages/blob/master/evga-precision-x1/tools/chocolateyInstall.ps1

Chocolatey's CI is still running Windows 2012r2.

I've stopped spending time fixing issues specifically for their CI. They're planning to release a modernized CI.

If you'd like to debug it, I'll happily accept a Pull Request

**Comment by koitsu** [comment]
What does a CI have to do with generating a Chocolatey package?

**Comment by javydekoning** [comment]
If the Chocolatey public CI does not pass the package is not published.

Like I said, the package is generated for Win 10/11 and works fine. It's just not listed on the public choco repo because of their CI.

**Comment by koitsu** [comment]
I maintain several Chocolatey packages myself and am very curious as to how/why the CI matters in this case.  What fails and why?  Can you show logs of the failure?

**Comment by javydekoning** [comment]
@koitsu , sure have a look here:

https://gist.github.com/choco-bot/0d35859de97a71a9778b43af16fd2b4a#file-install-txt-L549-L553

```
Could not create SSL/TLS secure channel
```

This indicates a TLS 1.2 handshake failure to me (See: https://learn.microsoft.com/en-us/answers/questions/825110/the-request-was-aborted-could-not-create-ssl-tls-s). 

But as you can see here:

https://github.com/javydekoning/chocolatey-fanatec-packages/blob/master/evga-precision-x1/tools/chocolateyInstall.ps1#L2

I did implement that. 

The validation test is really slow, and not easy (or even possible) to replicate in GitHub Actions.

**Comment by javydekoning** [comment]
p.s. I can replicate the issue on 2012r2, but it works fine on 2016 and up. 

Choco maintainers have been promising a modern CI for a while.

Personally I've moved on to WinGet which feels more modern and easier to maintain packages for.

**Comment by koitsu** [comment]
I actually understand this problem since I only recently (last week) switched to Windows 10.  I've been on Windows 7 for many years and am a sysadmin by day, so lots of experience with this.

EVGA uses a CDN that requires minimum TLSv1.1 (probably TLSv1.2) and refuses fall back to TLSv1.0 or SSLv3.  Providers like Cloudflare and CDN services like Akamari started requiring this some time ago.  Sure enough, EVGA uses Akamai as a CDN:

```
$ host storage.cdn.evga.com
storage.cdn.evga.com is an alias for storage.cdn.evga.com.edgekey.net.
storage.cdn.evga.com.edgekey.net is an alias for e8581.f.akamaiedge.net.
e8581.f.akamaiedge.net has address 23.203.227.212
```

Windows 7 (and thus Windows 2012r2) does not enable TLSv1.2 or v1.1 by default in [Schannel](https://learn.microsoft.com/en-us/windows-server/security/tls/tls-ssl-schannel-ssp-overview), but [it's easy to enable: two registry keys](https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392) do the job:
```
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v "DisabledByDefault" /t REG_DWORD /d 0 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client" /v "DisabledByDefault" /t REG_DWORD /d 0 /f
```

I've used the above for a very, very long time on Windows 7, as software like [foobar2000's component updater requires it](https://hydrogenaud.io/index.php?topic=118821.0) for the very same reasons (their back-end component server is what's requiring it).

I will bring this up with the Chocolatey people on their Discord server.  It should be as simple as them setting the keys and rebooting the system.

As for your "workaround": all that does is force use of TLSv1.2 (and no other fallback protocol) in .NET, it doesn't make the underlying Schannel layer "turn on" TLSv1.2 support.  PowerShell is C#-based, but uses Schannel; Schannel is entirely dependent on OS behaviour.

**Comment by javydekoning** [comment]
There is no restarting the server. The CI is ephemeral and runs on AppVeyor.

As I mentioned, they moved to 2019 in January so I can just resubmit and it will work now.

**Comment by koitsu** [comment]
> Seems the new CI was released: https://blog.chocolatey.org/2023/01/updating-package-services-image-win2019/.
> 
> I'll resubmit the package.
>
> ...
> The CI is ephemeral and runs on AppVeyor.

Interesting.  The more I deal with Chocolatey, the more surprised I become by things like this (re: them using Appveyor rather than their own stuff).

If you need any package vetting, let me know.

**Comment by koitsu** [comment]
Closing, as I have found other solutions (thank you for mentioning WinGet!).
