### ISSUE TITLE
Broken and outdated

### ISSUE THREAD

**Issue by barkap** [javydekoning/chocolatey-fanatec-packages#7]
Chocolately package version: 1.0.346
Latest: Fanatec Driver 381 (November 2020)

Right now the old (346) also cannot be installed:
```
Attempt to get headers for https://fanatec.com/media/unknown/a8/ff/14/Fanatec_64_driver_346.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://fanatec.com/media/unknown/a8/ff/14/Fanatec_64_driver_346.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading fanatec-driver 64 bit
  from 'https://fanatec.com/media/unknown/a8/ff/14/Fanatec_64_driver_346.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://fanatec.com/media/unknown/a8/ff/14/Fanatec_64_driver_346.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of fanatec-driver was NOT successful.
```

**Comment by javydekoning** [comment]
Thanks for reporting, I didn't notice 381 was published. I though it was still a prerelease version. 

I'll submit 381 for approval today!

**Comment by javydekoning** [comment]
I just pushed Fanalab v1.54.2, will work on the drivers today. Fanatec changed from distributing 32 and 64 bit MSI's to a single zip file. Making it slightly more difficult for me.

**Comment by javydekoning** [comment]
Fails validation, on 2012r2 automated tests. I tried implementing using AutoHotKey script but can't get `ControlClick, &Install, %winTitle%` to work. Sending keystrokes also seems to not work. 

Might needs some help on this.

![ahk issue](https://pbs.twimg.com/media/EqAasJSW4AAGqtR?format=jpg&name=large)

**Comment by javydekoning** [comment]
Latest version is now on Choco repo.
