### ISSUE TITLE
[EVGA Precision X1] outdated, is at 1.1.4 now

### ISSUE THREAD

**Issue by jtcmedia** [javydekoning/chocolatey-fanatec-packages#8]
As title states, this pkg needs updating.

**Comment by javydekoning** [comment]
Thanks @jtcmedia , EVGA has started to check for different headers breaking my `update.ps1`. I have pushed 1.1.4 now (pending verification) but need to fix auto-updater as well.

**Comment by javydekoning** [comment]
It's not a pretty workaround, but seems to work: https://github.com/javydekoning/chocolatey-fanatec-packages/commit/c970a112c08b2e55a86bc9720c09db3cc67bd646 

Pending automated Chocolatey automated reviews.

The `Get-EvgaRedirectUrl` function I created fails on PS7.1 (seems to ignore `-ea 0` for some reason). But that should not matter as CI runs on Windows Powershell (5.1). 

Keeping this open until reviewed by chocolatey.

**Comment by jtcmedia** [comment]
Great! Thanks @javydekoning
